### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by wasimbaig** [vichargrave/espcap#14]
(vespcap) ]# src/espcap.py --nic=eno16777984 --node=es1:9200 --count=100
[ERROR]  Traceback (most recent call last):
  File "src/espcap.py", line 294, in <module>
    main()
  File "/root/.virtualenvs/vespcap/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/root/.virtualenvs/vespcap/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/root/.virtualenvs/vespcap/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.virtualenvs/vespcap/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "src/espcap.py", line 275, in main
    live_capture(nic, bpf, node, chunk, count)
  File "src/espcap.py", line 210, in live_capture
    print '[ERROR] ', e
  File "/root/.virtualenvs/vespcap/lib/python2.7/site-packages/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers

this happens on file, dir or live capture

espcap to stdout seems to work just fine, so its something to do with elasticsearch

**Comment by wasimbaig** [comment]
curl -XGET 'http://es1:9200'
{
  "name" : "es1",
  "cluster_name" : "es01",
  "cluster_uuid" : "92HRt7D-Q8Gt8p1wZdG8Ug",
  "version" : {
    **"number" : "6.2.4",**
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

pip freeze
click==6.6
**elasticsearch==2.3.0**
futures==3.0.5
Logbook==0.12.5
lxml==3.6.0
py==1.4.31
pyshark==0.3.5
six==1.10.0
trollius==1.0.4
urllib3==1.16

Digging a bit further
https://github.com/elastic/elasticsearch-py/issues/496

It seems to be a version mismatch.
