### ISSUE TITLE
[ERROR] 'timestamp' - where is this error comming from?

### ISSUE THREAD

**Issue by perskes** [vichargrave/espcap#3]
Hey, I wonder if you have any idea about the problem I am facing:

````
root@debian:~/espcap# python3.7 src/espcap.py --file=test_pcaps/test_http.pcap --node=localhost:9200
Loading packet capture file(s)
test_pcaps/test_http.pcap
Running as user "root" and group "root". This could be dangerous.
[ERROR]  'timestamp'
[ERROR]  [priority,] message string
Traceback (most recent call last):
  File "src/espcap.py", line 77, in init_file_capture
    helpers.bulk(client=es, actions=index_packets(capture=capture), chunk_size=chunk, raise_on_error=True)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 300, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 212, in streaming_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 63, in _chunk_actions
    for action, data in actions:
  File "/root/espcap/src/indexer.py", line 30, in index_packets
    timestamp = int(packet['timestamp'])/1000
KeyError: 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/espcap.py", line 124, in main
    init_file_capture(es=es, tshark=tshark, pcap_files=pcap_files, chunk=chunk)
  File "src/espcap.py", line 81, in init_file_capture
    syslog.syslog(syslog.LOG_ERR, e)
TypeError: [priority,] message string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/espcap.py", line 141, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "src/espcap.py", line 136, in main
    syslog.syslog(syslog.LOG_ERR, e)
TypeError: [priority,] message string
tshark: An error occurred while printing packets: Broken pipe.

````

The command I used:

`python3.7 src/espcap.py --file=test_pcaps/test_http.pcap --node=localhost:9200`

I issued the command from ~/espcap and my elk-stack (7.x) is running on localhost:9200.
I followed your installation-guide and did everything as you described.

Running on debian 9

**Comment by perskes** [comment]
Tested it again with Debian 10 and elasticsearch 6:

Same error.
This time I did the ELK Setup myself, instead of using the bitnami VM.
Plus, the requirements in requirements-6.x.x require Elasticsearch 6.7.x and it's not available via pip.

Just mentioning what occured to me.

Any idea how to process? It appears that the "Timestamp" field in the packet generator could not be read/used.

**Comment by mdrouet** [comment]
Hi, 

Running into the same problem here.
```
root@ubuntu-dev:~/espcap/src# python3 espcap.py --file=../test_pcaps/test_http.pcap --node=localhost:9200
Loading packet capture file(s)
../test_pcaps/test_http.pcap
Running as user "root" and group "root". This could be dangerous.
[ERROR]  'timestamp'
[ERROR]  [priority,] message string
Traceback (most recent call last):
  File "espcap.py", line 77, in init_file_capture
    helpers.bulk(client=es, actions=index_packets(capture=capture), chunk_size=chunk, raise_on_error=True)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 300, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 212, in streaming_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 63, in _chunk_actions
    for action, data in actions:
  File "/root/espcap/src/indexer.py", line 30, in index_packets
    timestamp = int(packet['timestamp'])/1000
KeyError: 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "espcap.py", line 124, in main
    init_file_capture(es=es, tshark=tshark, pcap_files=pcap_files, chunk=chunk)
  File "espcap.py", line 81, in init_file_capture
    syslog.syslog(syslog.LOG_ERR, e)
TypeError: [priority,] message string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "espcap.py", line 141, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "espcap.py", line 136, in main
    syslog.syslog(syslog.LOG_ERR, e)
TypeError: [priority,] message string
tshark: An error occurred while printing packets: Broken pipe.
```

I'm on Ubuntu 18.04.3 LTS

* Rebuilt from fresh install ==> No problem from the ELK itself
* Checked pcap files ==> No problem
* Upgraded to the latest version of modules in requirements


Any idea ?

**Comment by perskes** [comment]
Nope, sorry. Decided to write my own script from scratch, with multiprocessing and bulk indexing. I work with a ton of data and it's just too slow. Plus, the amount of data in elasticsearch is a multitude of the data in the pcap, as pcap is highly compressed.

Once you figured out how to deal with the output of tshark its easy to write your script. I initially wanted to use this because it brought the whole elkstack in a single container, but it's actually easier to set up than expected!

**Comment by spanwich** [comment]
> Hi,
> 
> Running into the same problem here.
> 
> ```
> root@ubuntu-dev:~/espcap/src# python3 espcap.py --file=../test_pcaps/test_http.pcap --node=localhost:9200
> Loading packet capture file(s)
> ../test_pcaps/test_http.pcap
> Running as user "root" and group "root". This could be dangerous.
> [ERROR]  'timestamp'
> [ERROR]  [priority,] message string
> Traceback (most recent call last):
>   File "espcap.py", line 77, in init_file_capture
>     helpers.bulk(client=es, actions=index_packets(capture=capture), chunk_size=chunk, raise_on_error=True)
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 300, in bulk
>     for ok, item in streaming_bulk(client, actions, *args, **kwargs):
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 212, in streaming_bulk
>     actions, chunk_size, max_chunk_bytes, client.transport.serializer
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 63, in _chunk_actions
>     for action, data in actions:
>   File "/root/espcap/src/indexer.py", line 30, in index_packets
>     timestamp = int(packet['timestamp'])/1000
> KeyError: 'timestamp'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "espcap.py", line 124, in main
>     init_file_capture(es=es, tshark=tshark, pcap_files=pcap_files, chunk=chunk)
>   File "espcap.py", line 81, in init_file_capture
>     syslog.syslog(syslog.LOG_ERR, e)
> TypeError: [priority,] message string
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "espcap.py", line 141, in <module>
>     main()
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "espcap.py", line 136, in main
>     syslog.syslog(syslog.LOG_ERR, e)
> TypeError: [priority,] message string
> tshark: An error occurred while printing packets: Broken pipe.
> ```
> 
> I'm on Ubuntu 18.04.3 LTS
> 
> * Rebuilt from fresh install ==> No problem from the ELK itself
> * Checked pcap files ==> No problem
> * Upgraded to the latest version of modules in requirements
> 
> Any idea ?

The problem lies in tshark.py line 134 where it fails to verify line start with "index" checking.
So, for me I change to string.find()

Hope this helps.

**Comment by perskes** [comment]
It literally states "key error" thus, the key does not exist where the program requires it.
Add  a json.dumps(packet, indent=4) somewhere before that line and make sure it prints before the key error.

Check where the timestamp actually is (maybe its nestesd) and adapt the script or figure out why the key is not in the correct place. 

it's probably easier than you think.

**Comment by vichargrave** [comment]
Hi all.  I'll take a look at this issue on Ubuntu 18.04.3.  Sorry for the late response.

**Comment by vichargrave** [comment]
> Hi,
> 
> Running into the same problem here.
> 
> ```
> root@ubuntu-dev:~/espcap/src# python3 espcap.py --file=../test_pcaps/test_http.pcap --node=localhost:9200
> Loading packet capture file(s)
> ../test_pcaps/test_http.pcap
> Running as user "root" and group "root". This could be dangerous.
> [ERROR]  'timestamp'
> [ERROR]  [priority,] message string
> Traceback (most recent call last):
>   File "espcap.py", line 77, in init_file_capture
>     helpers.bulk(client=es, actions=index_packets(capture=capture), chunk_size=chunk, raise_on_error=True)
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 300, in bulk
>     for ok, item in streaming_bulk(client, actions, *args, **kwargs):
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 212, in streaming_bulk
>     actions, chunk_size, max_chunk_bytes, client.transport.serializer
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/helpers/actions.py", line 63, in _chunk_actions
>     for action, data in actions:
>   File "/root/espcap/src/indexer.py", line 30, in index_packets
>     timestamp = int(packet['timestamp'])/1000
> KeyError: 'timestamp'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "espcap.py", line 124, in main
>     init_file_capture(es=es, tshark=tshark, pcap_files=pcap_files, chunk=chunk)
>   File "espcap.py", line 81, in init_file_capture
>     syslog.syslog(syslog.LOG_ERR, e)
> TypeError: [priority,] message string
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "espcap.py", line 141, in <module>
>     main()
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "espcap.py", line 136, in main
>     syslog.syslog(syslog.LOG_ERR, e)
> TypeError: [priority,] message string
> tshark: An error occurred while printing packets: Broken pipe.
> ```
> 
> I'm on Ubuntu 18.04.3 LTS
> 
>     * Rebuilt from fresh install ==> No problem from the ELK itself
> 
>     * Checked pcap files ==> No problem
> 
>     * Upgraded to the latest version of modules in requirements
> 
> 
> Any idea ?

Are you using Elasticsearch 7.5?

**Comment by spanwich** [comment]
> Are you using Elasticsearch 7.5?

Hi,
My environment is Ubuntu 18.04.3 LTS, Elasticsearch 7.5 and "Python 3.7" which is different from your recommend python 2.7. However, I have found that using Elasticsearch 7.5 with Tshark command els flag feed out 2 rows for each packets which violates your program as I mentioned above. 
To be noted that, I think it occur because the logical check from Python 3.7, not your code.

**Comment by vichargrave** [comment]
You can use either Python 2.7 or 3.7.  I would do this all in a virtual environment.  That may help.  I'm still looking into this on my end.

**Comment by sirlatrom** [comment]
I've seen this issue with tshark 2.8.x fixed with tshark 3.0.x. 2.8.x is available in debian buster whereas 3.2.x is in testing, and 3.0.x in alpine 3.11 (3.2.x in alpine edge).

**Comment by ZeadAlkhonein** [comment]
i have encounter this issue and i have added a line in the code in the indexer.py 
made with every packet the next iterator

`def index_packets(capture):

    for packet in capture:
        packet = next(capture)
        timestamp = int(packet['timestamp'])/1000
        action = {
            '_op_type': 'index',
            '_index': 'packets-' + datetime.fromtimestamp(timestamp).strftime('%Y-%m-%d'),
            '_source': packet
        }
        yield action
 `
i hope this help
